### ISSUE TITLE
Customizing the auto-import folder name ?

### ISSUE THREAD

**Issue by mrleblanc101** [gitFoxCode/nuxt-icons#6]
Hi,
In my org, we use `assets/svg` for icons, would it be possible to add an option to customize the folder ?
Thanks

**Comment by gitFoxCode** [comment]
Currently this is not possible, but it's a great idea! In the next version there will be an option to choose your own folder name

**Comment by gitFoxCode** [comment]
@lisaschumann Hi, currently it is not possible to use a name other than "icons", this is due to many factors, I wanted first of all to get similar to Nuxt core system that "folder with this name automatically fetches things" etc., creating a special option to be able to customize the folder name would be problematic, because it would require reworking the module (currently uses import.meta.glob, which does not allow the use of variables). But for now you can:
- extract all icons directly to /icons, or
- put the custom folder into /icons and use `<nuxt-icon name="customFolderName/IconName" />`.
